name: Create a Pull Request
description: Create a Pull Request on Github
author: Nebeto

branding:
  icon: git-pull-request
  color: black

inputs:
  is-draft:
    description: Flag the Pull Request as a draft or not, default to true
    required: false
    default: true
  to-branch:
    description: Target branch, default to main
    required: false
    default: main
  assignees:
    description: Assignees
    required: false

outputs:
  id:
    description: ID of the created Pull Request
  url:
    description: URL of the created Pull Request

runs:
  using: node20
  main: dist/index.js
