name: Develop

on:
  workflow_dispatch:
  push:
    branches:
      - feat/**
      - fix/**
      - docs/**
      - ci/**
      - chore/**
      - test/**
      - perf/**
      - refactor/**
      - revert/**
      - style/**

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: develop-${{ github.ref_name }}
  cancel-in-progress: true

env:
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  ORGANIZATION_ID: ${{ github.repository_owner }}

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    name: Create a Pull Request
    steps:
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.ref }}
      - id: create-or-get-existing-draft-pull-request
        name: Create or get an existing draft Pull Request on Github
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
  check:
    runs-on: ubuntu-latest
    name: Check
    needs: create-pull-request
    strategy:
      matrix:
        command: ["lint", "test"]
        include:
          - artifact-name: reports-check-quality
            files: |
              reports-eslint-code.json
              reports-eslint-test.json
            command: lint
          - artifact-name: reports-check-testing
            files: lcov.info
            command: test
    steps:
      - id: checkout-code
        uses: actions/checkout@v4.2.2
      - id: setup-node
        uses: actions/setup-node@v4.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json
      - id: setup-dependencies
        name: Setup dependencies
        run: npm install
      - id: check-code
        name: Check code via "npm run ${{ matrix.command }}"
        run: npm run ${{ matrix.command }}
      - id: upload-reports
        name: Upload Reports
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.files }}
  report:
    runs-on: ubuntu-latest
    name: Report
    needs: check
    steps:
      - id: checkout-code
        uses: actions/checkout@v4.2.2
      - id: download-reports
        name: Download Reports
        uses: actions/download-artifact@v4.2.1
        with:
          pattern: reports-*
          merge-multiple: true
      - id: report-quality-sonarqube
        name: Report on SonarQube
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectVersion=${{ github.ref }}
            -Dsonar.organization=${{ env.ORGANIZATION_ID }}
