name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

env:
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  ORGANIZATION_ID: ${{ github.repository_owner }}
  PROJECT_ID: ${{ github.event.repository.name }}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      pr: ${{ steps.release.outputs.pr }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - id: release
        name: Release
        uses: googleapis/release-please-action@v4.2.0
        with:
          release-type: node
  report:
    runs-on: ubuntu-latest
    name: Report
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - id: checkout-code
        uses: actions/checkout@v4.2.2
      - id: setup-node
        uses: actions/setup-node@v4.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json
      - id: setup-dependencies
        name: Setup dependencies
        run: npm install
      - id: check-code
        name: Check code
        run: |
          npm run lint
          npm run test
      - id: report-quality-sonarqube
        name: Report on SonarQube
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectVersion=${{ needs.release.outputs.tag_name }}
            -Dsonar.organization=${{ env.ORGANIZATION_ID }}
            -Dsonar.links.ci=https://github.com/${{ env.ORGANIZATION_ID }}/${{ env.PROJECT_ID }}/actions
            -Dsonar.links.homepage=https://github.com/marketplace/actions/${{ env.PROJECT_ID }}
            -Dsonar.links.issue=https://github.com/${{ env.ORGANIZATION_ID }}/${{ env.PROJECT_ID }}/issues
            -Dsonar.links.scm=https://github.com/${{ env.ORGANIZATION_ID }}/${{ env.PROJECT_ID }}
