name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - dist/**

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  ORGANIZATION_ID: ${{ github.repository_owner }}
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  PROJECT_DESCRIPTION: ${{ vars.PROJECT_DESCRIPTION }}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      prs_created: ${{ steps.release.outputs.prs_created }}
      pr: ${{ steps.release.outputs.pr }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - id: release
        name: Release
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
  build:
    runs-on: ubuntu-latest
    name: Build
    needs: release
    if: ${{ needs.release.outputs.prs_created }}
    steps:
      - id: checkout-code
        uses: actions/checkout@v4
        with:
          ref: ${{ fromJSON(needs.release.outputs.pr).headBranchName }}
      - id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json
      - id: setup-dependencies
        name: Setup dependencies
        run: npm install
      - id: build-code
        name: Build
        run: npm run build
      - id: upload-artifact
        name: Upload Artifact
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./dist/
          git commit -m "build(main): prepare release"
          git push
  report-quality:
    runs-on: ubuntu-latest
    name: Report Quality
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - id: checkout-code
        uses: actions/checkout@v4
      - id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json
      - id: setup-dependencies
        name: Setup dependencies
        run: npm install
      - id: build-code
        name: Build
        run: |
          npm run lint
          npm run test
      - id: report-quality-sonarqube
        name: Report on SonarQube
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
            -Dsonar.projectVersion=${{ needs.release.outputs.tag_name }}
            -Dsonar.organization=${{ env.ORGANIZATION_ID }}
            -Dsonar.projectKey=${{ env.ORGANIZATION_ID }}_${{ env.PROJECT_ID }}
            -Dsonar.projectDescription=${{ env.PROJECT_DESCRIPTION }}
            -Dsonar.links.ci=https://github.com/${{ env.ORGANIZATION_ID }}/${{ env.PROJECT_ID }}/actions
            -Dsonar.links.homepage=https://github.com/marketplace/actions/${{ env.PROJECT_ID }}
            -Dsonar.links.issue=https://github.com/${{ env.ORGANIZATION_ID }}/${{ env.PROJECT_ID }}/issues
            -Dsonar.links.scm=https://github.com/${{ env.ORGANIZATION_ID }}/${{ env.PROJECT_ID }}
